version: "2"
services:
  app:
    container_name: webdevapidocker
    restart: always
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ~/data/db:/data/db
    ports:
      - "27017:27017"
