version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ~/data/db:/data/db
    ports:
      - "27017:27017"
  app:
    container_name: webdevapidocker
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo